### ISSUE TITLE
Create colored output

### ISSUE THREAD

**Issue by architapatelis** [TheInvalidNonce/weatherbot-cli-app#1]
@TheInvalidNonce I was trying to find open source projects I can contribute to when I came across this gem. It's a cool gem you've made, I was testing the cli and I realized that it would be nice to have a menu with colored output - here is a screenshot of what I am talking about https://photos.app.goo.gl/02lxhzlGCOR5l8Rw2

I think that it would be a good enhancement, it  would make it easier to read the possible commands. If it's ok with you I would like to like to submit a pull request with these changes.

**Comment by grey-lock** [comment]
Hi @architapatelis,

Thank you for the feedback! You are more than welcome to submit a pull request for this project! I am open to any improvements!
